spring.application.name=LTRMS-Backend

#Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=savageyt6@gmail.com
spring.mail.password=jjycsxulsupmkvpx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#SSL Configuration
server.port=9999
server.ssl.enabled=true
server.ssl.key-store:src/main/resources/static/SSL/bootsecurity.p12
server.ssl.key-store-password:security
server.ssl.KeyStoreType:PKCS12
server.ssl.KeyAlias:bootsecurity



file.upload-dir=C:/app/uploads


#logging.level.root=INFO
#logging.level.com.example.LTRMS_Backend=DEBUG
#logging.file.name=logs/ltrms-backend.log
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

